name: Deploy APT repo to GitHub Pages

on:
  push:
    branches:
      - main  # usa "master" si tu rama principal se llama así

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Subir archivos del repositorio
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Publica todo, incluido index.html y la carpeta dists

      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v4
